### ISSUE TITLE
Build fails on windows, filename incorrect in google_cloud_bucket_cConfig.cmake

### ISSUE THREAD

**Issue by applyinnovations** [offscale/google-cloud-bucket-c#1]
```
CMake Error at build/vcpkg_installed/x64-windows/share/google_cloud_bucket_c/google_cloud_bucket_cConfig.cmake:11 (include):
  include could not find requested file:

    C:/Users/a/Projects/archimedes-ui/build/vcpkg_installed/x64-windows/share/google_cloud_bucket_c/google-cloud-bucket-cTargets.cmake
```

Change line 11 from 
`include ( "${CMAKE_CURRENT_LIST_DIR}/google-cloud-bucket-cTargets.cmake" )`
to 
`include ( "${CMAKE_CURRENT_LIST_DIR}/google_cloud_bucket_cTargets.cmake" )`

https://github.com/offscale/google-cloud-bucket-c/blob/611bef746802403ac3082e9c627e77e992eecdad/cmake/Config.cmake.in#L4

**Comment by SamuelMarks** [comment]
Oh yes I renamed it because the underscore was playing havoc with vcpkg, let me fix that
